collections_dir: our_collections
collections:
  members:
    output: true
  publications:
    output: true
  joins:
    output: true

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
      
exclude: 
  - tmp/
  - vendor/
  - readme.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship
